<a href="https://colab.research.google.com/github/mohitgupta82345-sys/Data-science-and-visualization/blob/main/Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:

import pandas as pd
pd.__version__

'2.2.3'

In [21]:
sales = pd.Series([2,3,5])

In [22]:
sales

0    2
1    3
2    5
dtype: int64

In [23]:
sales[2]

np.int64(5)

In [24]:
sales[0:4]

0    2
1    3
2    5
dtype: int64

In [25]:
sales.index

RangeIndex(start=0, stop=3, step=1)

In [26]:
sales.values

array([2, 3, 5])

In [29]:
sales.dtype

dtype('int64')

In [33]:
sales.head(2)

0    2
1    3
dtype: int64

In [36]:
sales.tail(2)

1    3
2    5
dtype: int64

In [38]:
sales.sort_values()

0    2
1    3
2    5
dtype: int64

In [39]:
sales1 = pd.Series([2,1,5,7,3,6,9,8,10])

In [40]:
sales1

0     2
1     1
2     5
3     7
4     3
5     6
6     9
7     8
8    10
dtype: int64

In [44]:
sales.count()
sales1.count()

np.int64(9)

In [45]:
sales.isnull()

0    False
1    False
2    False
dtype: bool

In [47]:
sales.notnull()

0    True
1    True
2    True
dtype: bool

In [50]:
sales + 2

0    4
1    5
2    7
dtype: int64

In [51]:
sales**2

0     4
1     9
2    25
dtype: int64

In [52]:
sales - 1

0    1
1    2
2    4
dtype: int64

In [53]:
sales_missing = pd.Series([2,None,5])

In [54]:
sales_missing

0    2.0
1    NaN
2    5.0
dtype: float64

In [58]:
sales_missing.fillna(1)

0    2.0
1    1.0
2    5.0
dtype: float64

In [61]:
data = pd.DataFrame({
    'Name' : ['anshul' , 'mehul'] ,
    'id no' : ['03' , '21']
})

In [63]:
data

     Name id no
0  anshul    03
1   mehul    21